model:
  target: "prior.diffusion_prior.DiffusionPrior"
  params:
    parameterization: "x0"
    scale_embeddings: true
    optimizer_config:
      target: "torch.optim.AdamW"
      params:
        lr: 2e-4
        betas: [0.9, 0.999]
        eps: 1e-08
        weight_decay: 0.01
    lr_scheduler_config:
      target: "torch.optim.lr_scheduler.CosineAnnealingWarmRestarts"
      params:
        T_0: 50_000
        eta_min: 0.0
    language_model_config:
      target: "prior.adapter.OpenClipAdapter"
      params:
        path: "hf-hub:laion/CLIP-ViT-B-32-laion2B-s34B-b79K"
    noise_scheduler_config:
      target: "prior.gaussian_diffusion.NoiseScheduler"
      params:
        beta_schedule: "cosine"
        timesteps: 1000
        loss_type: "l2"
    prior_transformer_config:
      target: "prior.prior_transformer.PriorTransformer"
      params:
        ctx_len: 77
        emb_dim: 512
        num_layers: 8
        num_heads: 8
        final_ln: true
        clip_dim: 512
        dropout: 0.00
trainer:
  train_data_urls: "pipe: aws s3 cp --quiet s3://stability-west/laion_coyo_dedupedv3/{00000..99998}.tar -"
  val_data_urls: "pipe: aws s3 cp --quiet s3://stability-west/laion_coyo_dedupedv3/99999.tar -"
  epoch_length: 2037612045
  train_batch_size: 256
  valid_batch_size: 32
  wandb_project: "prior-testing"
  precision: "bf16-mixed"
  max_epochs: 1
  gradient_clip_val: 0.5
  accumulate_grad_batches: 1
  limit_val_batches: 1
  val_check_interval: 100
  enable_checkpointing: false
  val_check_interval: 100
  enable_checkpointing: true
  checkpoint_dirpath: "checkpoints"
  checkpoint_save_top_k: 4
  checkpoint_monitor: "global_step"
  checkpoint_mode: "max"
  checkpoint_filename: "prior-big-g-{epoch:02d}-{global_step:06d}"
  checkpoint_train_time_interval_minutes: 60